# Generated by Django 4.2.4 on 2023-09-20 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
