# Generated by Django 4.2.4 on 2023-09-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='start_time',
        ),
    ]
